app = "polystocks-trading-bot"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile.bot"

[env]
  NODE_ENV = "production"

[[services]]
  internal_port = 8080
  protocol = "tcp"

[deploy]
  strategy = "immediate"
